import type { NextPage } from 'next';
import Head from 'next/head';
// eslint-disable-next-line import/no-extraneous-dependencies
import { Container, Grid } from '@mui/material';
import { Products } from '../common/types/@appTypes';
import fetchData from '../common/utils/hooks/fetchData';
import ProductsList from '../common/components/productList/ProductsList';
import SideBar from '../modules/homePage/sideBar';

type Props = {
  products: Products;
};

const Home: NextPage<Props> = ({ products }) => (
  <Container
    maxWidth="xl"
    sx={{ backgroundColor: 'secondary.main', height: '100%' }}
  >
    <Head>
      <title>Haysubi</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    {/* -------------------------------------------------------------------------------- */}
    <Grid
      container
      component="main"
      sx={{
        backgroundColor: '#eee',
      }}
    >
      <Grid md={3} xs={12} item>
        <SideBar />
      </Grid>
      <Grid md={9} item>
        <ProductsList products={products} />
      </Grid>
    </Grid>
  </Container>
);

export default Home;

export const getStaticProps = async () => {
  let returnObject;

  try {
    const products: Products = await fetchData<Products>();

    returnObject = {
      props: {
        products,
      },
      revalidate: 20,
    };
  } catch (e) {
    returnObject = { notFound: true };
  }
  return returnObject;
};
